# Generated by Django 5.2.12 on 2026-04-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_videoupload_processed_at_videoupload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='attentive_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='distracted_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='neutral_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='sleepy_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='student_count',
            field=models.IntegerField(default=0),
        ),
    ]
