# Generated by Django 5.2.12 on 2026-04-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_videoupload_attentive_pct_videoupload_distracted_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='heatmap_image',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/'),
        ),
    ]
