# Generated by Django 5.2.13 on 2026-04-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_classroom_analysisreport_videoupload_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='hand_raises_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='phone_usage_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='talking_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='webcamsession',
            name='hand_raises',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webcamsession',
            name='phone_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webcamsession',
            name='talking',
            field=models.IntegerField(default=0),
        ),
    ]
