# Generated by Django 5.2.13 on 2026-04-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_videoupload_hand_raises_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='processing_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
