# Generated by Django 5.2.13 on 2026-04-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_videoupload_estimated_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='camera_angle',
            field=models.IntegerField(choices=[(0, '0° (Horizontal)'), (90, '90° (Clockwise)'), (180, '180° (Inverted)'), (270, '270° (Counter-Clockwise)')], default=0),
        ),
    ]
