# Generated by Django 5.2.13 on 2026-04-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_videoupload_camera_angle'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='engagement_timeline',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
